<a href="https://colab.research.google.com/github/RheyMartt/CCMACLRL_EXERCISE_COM222ML/blob/main/exercise1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPHY

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr[0]

1

In [6]:
arr[2]

3

In [7]:
arr[1]

2

In [9]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
arr.ndim

2

In [11]:
arr.itemsize

8

In [12]:
arr.shape

(3, 2)

In [13]:
arr = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
arr.dtype

dtype('float64')

In [14]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [17]:
arr.shape

(5,)

#STRING FUNCTIONS

In [18]:
arr1 = np.array(["Hey", "Hi"])
arr2 = np.array(["abc", "xyz"])

In [21]:
arrstring = np.char.add(arr1, arr2)
print(arr1)
print(arr2)

['Hey' 'Hi']
['abc' 'xyz']


In [23]:
arrstring = np.char.multiply(arr1, 2)
arrstring

array(['HeyHey', 'HiHi'], dtype='<U6')

In [25]:
arr1 = np.char.upper(arr1)
arr1

array(['HEY', 'HI'], dtype='<U3')

#ARRAY MANIPULATION

In [26]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr3 = np.arange(20)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
arr3 = arr3.reshape(4,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
arr3 = arr3.reshape(10,2)
arr3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
arr3 = arr3.reshape(2,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
arr3 = arr3.reshape(20,1)
arr3

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [46]:
arr3 [0][0]

0

In [51]:
arr3 = np.arange(20).reshape(4,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
transposedarr = np.transpose(arr3)
transposedarr

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#ARITHMETIC OPERATIONS

In [55]:
a = np.arange(9).reshape (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
b = np.multiply(a, 3)
b

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [57]:
c = np.subtract( a, b)
c

array([[  0,  -2,  -4],
       [ -6,  -8, -10],
       [-12, -14, -16]])

In [58]:
d = np.add(a, b)
d

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32]])

#OTHER FUNCTIONS

In [62]:
a = np.linspace(1, 15, 30)
a

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

In [66]:
a = np.array([(1,2,3), (4,5,6)])
print(a.sum (axis=1))

[ 6 15]


In [67]:
a = np.array([(1,2,3), (4,5,6)])
print(a.sum (axis=0))

[5 7 9]


In [68]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [69]:
print(np.std(a))

1.707825127659933
